# Generated by Django 2.1.7 on 2020-07-01 20:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Status', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 1, 21, 37, 30, 845892)),
        ),
        migrations.AlterField(
            model_name='status',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts'),
        ),
    ]
