# Generated by Django 2.1.7 on 2020-07-01 20:41

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Status', '0002_auto_20200701_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='likes',
            field=models.ManyToManyField(related_name='likes_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messages',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 1, 21, 41, 3, 173552)),
        ),
    ]
